/**
 * AUTO-GENERATED BY scripts/codegen-capabilities.ts — DO NOT EDIT.
 *
 * 来源:packages/capability/manifests/audio.manifest.json
 * 重跑:pnpm codegen
 *
 * 此文件提供精确字面量联合类型 BuiltinCapabilityName,
 * 用于 IDE 自动补全与编译期拼写检查。
 *
 * 注意:
 * - `CapabilityName`(见 capability.ts)仍是 `string` 别名,
 *   接受任意能力名(含第三方 plugin 注册的自定义能力)
 * - `BuiltinCapabilityName` 是已知内置能力的字面量子集,
 *   可作为 `CapabilityName` 的精确化类型
 */
export type BuiltinCapabilityName =
  | 'audio.trim'
  | 'audio.normalize'
  | 'audio.merge'
  | 'audio.transcode';

/** 全部内置能力名常量数组(运行时校验 / 枚举用) */
export const BUILTIN_CAPABILITY_NAMES: readonly BuiltinCapabilityName[] = [
  'audio.trim',
  'audio.normalize',
  'audio.merge',
  'audio.transcode',
];
