/**
 * gen-version.mjs — 生成 wasm 资产版本常量(版本锁定,见设计文档 D4)
 *
 * 背景:AVIF 编码器 glue 代码(avif-worker.ts 打包进消费方)与 wasm 二进制
 * (运行时 fetch)必须来自同一 @lokvis/engine-image 版本,否则升级
 * @jsquash/avif 后会出现 glue/wasm ABI 漂移。默认 CDN URL 因此必须
 * 版本锁定:`@lokvis/engine-image@{version}/dist/wasm/avif.wasm`。
 *
 * 纯 tsc 构建无法 import ../package.json(rootDir 约束),故由本脚本
 * 把 package.json 的 version 物化为 src 下的生成模块,供 wasm-config.ts 引用。
 *
 * 接入点:根 `pnpm codegen`(见根 package.json,与 codegen-capabilities 串联),
 * 因此 `pnpm build` 会在 turbo 编译前刷新本文件;生成文件随仓库提交,
 * 保证 typecheck / 直接 build 无需先跑 codegen。
 *
 * 失败语义:package.json 不可读时非零退出,阻断 codegen。
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const pkgDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(await readFile(path.join(pkgDir, 'package.json'), 'utf8'));

const out = path.join(pkgDir, 'src', 'wasm', 'wasm-asset-version.generated.ts');
const content = `/**
 * AUTO-GENERATED BY scripts/gen-version.mjs — DO NOT EDIT.
 *
 * 来源:packages/engine-image/package.json 的 version 字段
 * 重跑:pnpm codegen(或 node packages/engine-image/scripts/gen-version.mjs)
 *
 * 用于构造版本锁定的 AVIF wasm CDN URL(见 docs/reports/20260724-engine-wasm-avif-encoder.md D4),
 * 确保 wasm 二进制版本与打包进消费方的 glue 代码版本一致,防止 ABI 漂移。
 */
export const ENGINE_IMAGE_VERSION = '${pkg.version}';
`;

await writeFile(out, content, 'utf8');
console.log(`[gen-version] wasm-asset-version.generated.ts → ${pkg.version}`);
