/**
 * AUTO-GENERATED BY scripts/codegen-mcp-tools.ts — DO NOT EDIT.
 *
 * 来源：packages/capability/manifests/*.manifest.json (7 manifests)
 *       + @lokvis/data-formats (14 format records)
 * 重跑：pnpm codegen
 *
 * MCP 工具元数据（描述 + 能力名映射）。
 * 手工覆盖位：tools/manual-overrides.ts（MCP 特有 inputSchema / 描述增强）。
 */

export interface GeneratedToolMeta {
  /** MCP tool 名（如 lokvis_image_resize） */
  name: string;
  /** 对应能力名（如 image.resize） */
  capability: string;
  /** 工具描述（manifest 描述 + 格式约束） */
  description: string;
}

export const GENERATED_TOOL_META: GeneratedToolMeta[] = [
  {
    name: 'lokvis_ai_ocr',
    capability: 'ai.ocr',
    description: 'Extract text from image or PDF using OCR',
  },
  {
    name: 'lokvis_ai_caption',
    capability: 'ai.caption',
    description: 'Generate a text caption for an image',
  },
  {
    name: 'lokvis_ai_background_remove',
    capability: 'ai.background-remove',
    description: 'Remove background from image, producing a transparent PNG/WebP',
  },
  {
    name: 'lokvis_ai_generate_workflow',
    capability: 'ai.generate-workflow',
    description: 'Generate a workflow from a natural-language prompt',
  },
  {
    name: 'lokvis_ai_optimize_workflow',
    capability: 'ai.optimize-workflow',
    description: 'Optimize an existing workflow for performance or cost',
  },
  {
    name: 'lokvis_ai_diagnose_error',
    capability: 'ai.diagnose-error',
    description: 'Diagnose a workflow execution error and suggest remediation',
  },
  {
    name: 'lokvis_audio_trim',
    capability: 'audio.trim',
    description: 'Trim audio to a time range',
  },
  {
    name: 'lokvis_audio_normalize',
    capability: 'audio.normalize',
    description: 'Normalize audio loudness to a target level',
  },
  {
    name: 'lokvis_audio_merge',
    capability: 'audio.merge',
    description: 'Merge multiple audio clips into one',
  },
  {
    name: 'lokvis_audio_transcode',
    capability: 'audio.transcode',
    description: 'Transcode audio to another format / codec',
  },
  {
    name: 'lokvis_image_resize',
    capability: 'image.resize',
    description: 'Resize image to specified dimensions Supported image formats: Animated PNG, AVIF, BMP, GIF, HEIC, ICO, JPEG, JPEG 2000, JPEG XL, PNG, Quite OK Image, SVG, TIFF, WebP. Format features: alpha, animation, exif, hdr, icc-profile, interlacing, lossless, lossy, multi-page, progressive, vector.',
  },
  {
    name: 'lokvis_image_compress',
    capability: 'image.compress',
    description: 'Compress image with specified quality Supported image formats: Animated PNG, AVIF, BMP, GIF, HEIC, ICO, JPEG, JPEG 2000, JPEG XL, PNG, Quite OK Image, SVG, TIFF, WebP. Format features: alpha, animation, exif, hdr, icc-profile, interlacing, lossless, lossy, multi-page, progressive, vector.',
  },
  {
    name: 'lokvis_image_convert',
    capability: 'image.convert',
    description: 'Convert image to another format Supported image formats: Animated PNG, AVIF, BMP, GIF, HEIC, ICO, JPEG, JPEG 2000, JPEG XL, PNG, Quite OK Image, SVG, TIFF, WebP. Format features: alpha, animation, exif, hdr, icc-profile, interlacing, lossless, lossy, multi-page, progressive, vector.',
  },
  {
    name: 'lokvis_image_crop',
    capability: 'image.crop',
    description: 'Crop image to a region Supported image formats: Animated PNG, AVIF, BMP, GIF, HEIC, ICO, JPEG, JPEG 2000, JPEG XL, PNG, Quite OK Image, SVG, TIFF, WebP. Format features: alpha, animation, exif, hdr, icc-profile, interlacing, lossless, lossy, multi-page, progressive, vector.',
  },
  {
    name: 'lokvis_image_rotate',
    capability: 'image.rotate',
    description: 'Rotate image by degrees Supported image formats: Animated PNG, AVIF, BMP, GIF, HEIC, ICO, JPEG, JPEG 2000, JPEG XL, PNG, Quite OK Image, SVG, TIFF, WebP. Format features: alpha, animation, exif, hdr, icc-profile, interlacing, lossless, lossy, multi-page, progressive, vector.',
  },
  {
    name: 'lokvis_image_flip',
    capability: 'image.flip',
    description: 'Flip image horizontally or vertically Supported image formats: Animated PNG, AVIF, BMP, GIF, HEIC, ICO, JPEG, JPEG 2000, JPEG XL, PNG, Quite OK Image, SVG, TIFF, WebP. Format features: alpha, animation, exif, hdr, icc-profile, interlacing, lossless, lossy, multi-page, progressive, vector.',
  },
  {
    name: 'lokvis_image_watermark',
    capability: 'image.watermark',
    description: 'Add text or image watermark Supported image formats: Animated PNG, AVIF, BMP, GIF, HEIC, ICO, JPEG, JPEG 2000, JPEG XL, PNG, Quite OK Image, SVG, TIFF, WebP. Format features: alpha, animation, exif, hdr, icc-profile, interlacing, lossless, lossy, multi-page, progressive, vector.',
  },
  {
    name: 'lokvis_image_background',
    capability: 'image.background',
    description: 'Set background color (for transparent images) Supported image formats: Animated PNG, AVIF, BMP, GIF, HEIC, ICO, JPEG, JPEG 2000, JPEG XL, PNG, Quite OK Image, SVG, TIFF, WebP. Format features: alpha, animation, exif, hdr, icc-profile, interlacing, lossless, lossy, multi-page, progressive, vector.',
  },
  {
    name: 'lokvis_image_filter',
    capability: 'image.filter',
    description: 'Apply preset filter (grayscale, invert, sepia, blur) Supported image formats: Animated PNG, AVIF, BMP, GIF, HEIC, ICO, JPEG, JPEG 2000, JPEG XL, PNG, Quite OK Image, SVG, TIFF, WebP. Format features: alpha, animation, exif, hdr, icc-profile, interlacing, lossless, lossy, multi-page, progressive, vector.',
  },
  {
    name: 'lokvis_image_favicon',
    capability: 'image.favicon',
    description: 'Generate multi-size ICO favicon from image Supported image formats: Animated PNG, AVIF, BMP, GIF, HEIC, ICO, JPEG, JPEG 2000, JPEG XL, PNG, Quite OK Image, SVG, TIFF, WebP. Format features: alpha, animation, exif, hdr, icc-profile, interlacing, lossless, lossy, multi-page, progressive, vector.',
  },
  {
    name: 'lokvis_pdf_merge',
    capability: 'pdf.merge',
    description: 'Merge multiple PDF files into one',
  },
  {
    name: 'lokvis_pdf_split',
    capability: 'pdf.split',
    description: 'Split a PDF into multiple files by page count or ranges',
  },
  {
    name: 'lokvis_pdf_compress',
    capability: 'pdf.compress',
    description: 'Compress a PDF to reduce file size',
  },
  {
    name: 'lokvis_pdf_rotate',
    capability: 'pdf.rotate',
    description: 'Rotate pages of a PDF by 90/180/270 degrees',
  },
  {
    name: 'lokvis_pdf_watermark',
    capability: 'pdf.watermark',
    description: 'Add a text watermark to a PDF',
  },
  {
    name: 'lokvis_pdf_add_page_numbers',
    capability: 'pdf.add-page-numbers',
    description: 'Add page numbers to a PDF',
  },
  {
    name: 'lokvis_pdf_ocr',
    capability: 'pdf.ocr',
    description: 'Extract text from a PDF via OCR',
  },
  {
    name: 'lokvis_pdf_sign',
    capability: 'pdf.sign',
    description: 'Digitally sign a PDF with a certificate',
  },
  {
    name: 'lokvis_video_compress',
    capability: 'video.compress',
    description: 'Compress video with specified bitrate / crf / scale',
  },
  {
    name: 'lokvis_video_transcode',
    capability: 'video.transcode',
    description: 'Transcode video to another format / codec',
  },
  {
    name: 'lokvis_video_trim',
    capability: 'video.trim',
    description: 'Trim video to a time range',
  },
  {
    name: 'lokvis_video_merge',
    capability: 'video.merge',
    description: 'Merge multiple video clips into one',
  },
  {
    name: 'lokvis_video_extract_audio',
    capability: 'video.extract-audio',
    description: 'Extract audio track from video',
  },
  {
    name: 'lokvis_video_to_gif',
    capability: 'video.to-gif',
    description: 'Convert video (or a segment) to animated GIF',
  },
  {
    name: 'lokvis_video_screenshot',
    capability: 'video.screenshot',
    description: 'Capture a frame from video at a given timestamp',
  },
];
