/**
 * AUTO-GENERATED BY scripts/codegen-capabilities.ts — DO NOT EDIT.
 *
 * 来源:packages/capability/manifests/ai.manifest.json
 * 重跑:pnpm codegen
 *
 * 与手写版本 packages/capability/src/presets/ai.ts 逐字段对应;
 * W4.3 完成迁移后,手写版本将被删除,本文件成为唯一来源。
 */
import type { Capability } from '@lokvis/schema';

export const AI_OCR: Capability = {
  name: 'ai.ocr',
  description: 'Extract text from image or PDF using OCR',
  inputTypes: ['image', 'pdf'],
  outputTypes: ['text'],
  params: [
    {
      name: 'language',
      type: 'string',
      required: false,
      description: 'OCR language code (e.g. eng, chi)',
    },
    {
      name: 'format',
      type: 'enum',
      default: 'text',
      values: ['text', 'json', 'structured'],
      description: 'Output format of OCR result',
    },
  ],
  performance: 'slow',
  batchable: true,
};

export const AI_CAPTION: Capability = {
  name: 'ai.caption',
  description: 'Generate a text caption for an image',
  inputTypes: ['image'],
  outputTypes: ['text'],
  params: [
    {
      name: 'maxTokens',
      type: 'number',
      required: false,
      min: 1,
      description: 'Max tokens for generated caption',
    },
    { name: 'language', type: 'string', required: false, description: 'Caption language' },
  ],
  performance: 'slow',
  batchable: true,
};

export const AI_BACKGROUND_REMOVE: Capability = {
  name: 'ai.background-remove',
  description: 'Remove background from image, producing a transparent PNG/WebP',
  inputTypes: ['image'],
  outputTypes: ['image'],
  params: [
    {
      name: 'format',
      type: 'enum',
      default: 'png',
      values: ['png', 'webp'],
      description: 'Output image format (transparent)',
    },
  ],
  performance: 'slow',
  batchable: true,
};

export const AI_GENERATE_WORKFLOW: Capability = {
  name: 'ai.generate-workflow',
  description: 'Generate a workflow from a natural-language prompt',
  inputTypes: [],
  outputTypes: ['data'],
  params: [
    {
      name: 'prompt',
      type: 'string',
      required: true,
      description: 'Natural-language description of the desired workflow',
    },
    {
      name: 'contextAssetIds',
      type: 'array',
      required: false,
      items: 'string',
      description: 'Optional context asset IDs',
    },
  ],
  performance: 'slow',
  batchable: false,
  mcpExposure: 'public',
};

export const AI_OPTIMIZE_WORKFLOW: Capability = {
  name: 'ai.optimize-workflow',
  description: 'Optimize an existing workflow for performance or cost',
  inputTypes: ['data'],
  outputTypes: ['data'],
  params: [
    {
      name: 'workflow',
      type: 'object',
      required: true,
      description: 'Workflow definition to optimize',
    },
  ],
  performance: 'slow',
  batchable: false,
  mcpExposure: 'public',
};

/** 所有内置 ai 能力预设(由 codegen 从 manifest 生成) */
export const AI_CAPABILITIES: Capability[] = [
  AI_OCR,
  AI_CAPTION,
  AI_BACKGROUND_REMOVE,
  AI_GENERATE_WORKFLOW,
  AI_OPTIMIZE_WORKFLOW,
];
