/**
 * AUTO-GENERATED BY scripts/codegen-capabilities.ts — DO NOT EDIT.
 *
 * 来源:packages/capability/manifests/archive.manifest.json
 * 重跑:pnpm codegen
 */
import type { Capability } from '@lokvis/schema';

export const ARCHIVE_ZIP: Capability = {
  name: 'archive.zip',
  description: 'Pack multiple assets into a single zip archive',
  inputTypes: ['image', 'video', 'audio', 'pdf', 'text', 'data'],
  outputTypes: ['data'],
  params: [
    {
      name: 'names',
      type: 'array',
      required: false,
      items: 'string',
      description: '各输入条目在归档内的文件名(按输入顺序);缺省按 file-{index} 生成',
    },
    {
      name: 'level',
      type: 'number',
      default: 6,
      min: 0,
      max: 9,
      description: 'DEFLATE 压缩级别 (0 仅存储 - 9 最大压缩)',
    },
  ],
  performance: 'medium',
  batchable: false,
};

export const ARCHIVE_UNZIP: Capability = {
  name: 'archive.unzip',
  description: 'Extract a zip archive into multiple assets',
  inputTypes: ['data'],
  outputTypes: ['data'],
  params: [],
  performance: 'medium',
  batchable: true,
};

export const ARCHIVE_LIST: Capability = {
  name: 'archive.list',
  description: 'List entries of a zip archive as a JSON data asset',
  inputTypes: ['data'],
  outputTypes: ['data'],
  params: [],
  performance: 'fast',
  batchable: true,
};

/** 所有内置 archive 能力预设(由 codegen 从 manifest 生成) */
export const ARCHIVE_CAPABILITIES: Capability[] = [
  ARCHIVE_ZIP,
  ARCHIVE_UNZIP,
  ARCHIVE_LIST,
];
