/**
 * AUTO-GENERATED BY scripts/codegen-capabilities.ts — DO NOT EDIT.
 *
 * 来源:packages/capability/manifests/audio.manifest.json
 * 重跑:pnpm codegen
 *
 * 与手写版本 packages/capability/src/presets/audio.ts 逐字段对应;
 * W4.3 完成迁移后,手写版本将被删除,本文件成为唯一来源。
 */
import type { Capability } from '@lokvis/schema';

export const AUDIO_TRIM: Capability = {
  name: 'audio.trim',
  description: 'Trim audio to a time range',
  inputTypes: ['audio'],
  outputTypes: ['audio'],
  params: [
    { name: 'start', type: 'number', required: true, min: 0, description: 'Start time in seconds' },
    { name: 'end', type: 'number', required: true, min: 0, description: 'End time in seconds' },
  ],
  performance: 'medium',
  batchable: true,
};

export const AUDIO_NORMALIZE: Capability = {
  name: 'audio.normalize',
  description: 'Normalize audio loudness to a target level',
  inputTypes: ['audio'],
  outputTypes: ['audio'],
  params: [
    { name: 'level', type: 'number', required: false, description: 'Target loudness in dB' },
  ],
  performance: 'medium',
  batchable: true,
};

export const AUDIO_MERGE: Capability = {
  name: 'audio.merge',
  description: 'Merge multiple audio clips into one',
  inputTypes: ['audio'],
  outputTypes: ['audio'],
  params: [
    {
      name: 'format',
      type: 'enum',
      default: 'mp3',
      values: ['mp3', 'wav', 'ogg', 'aac'],
      description: 'Output audio format',
    },
  ],
  performance: 'slow',
  batchable: false,
};

export const AUDIO_TRANSCODE: Capability = {
  name: 'audio.transcode',
  description: 'Transcode audio to another format / codec',
  inputTypes: ['audio'],
  outputTypes: ['audio'],
  params: [
    {
      name: 'format',
      type: 'enum',
      required: true,
      values: ['mp3', 'wav', 'ogg', 'aac'],
      description: 'Target audio format',
    },
    {
      name: 'bitrate',
      type: 'number',
      required: false,
      min: 0,
      description: 'Target bitrate in bps',
    },
  ],
  performance: 'slow',
  batchable: true,
};

/** 所有内置 audio 能力预设(由 codegen 从 manifest 生成) */
export const AUDIO_CAPABILITIES: Capability[] = [
  AUDIO_TRIM,
  AUDIO_NORMALIZE,
  AUDIO_MERGE,
  AUDIO_TRANSCODE,
];
