/**
 * AUTO-GENERATED BY scripts/codegen-capabilities.ts — DO NOT EDIT.
 *
 * 来源:packages/capability/manifests/developer.manifest.json
 * 重跑:pnpm codegen
 */
import type { Capability } from '@lokvis/schema';

export const DEV_INSPECT_CAPABILITIES: Capability = {
  name: 'developer.inspect.capabilities',
  description: 'List all registered capabilities',
  inputTypes: ['data'],
  outputTypes: ['data'],
  params: [],
  performance: 'fast',
  batchable: false,
};

export const DEV_INSPECT_ASSET: Capability = {
  name: 'developer.inspect.asset',
  description: 'Inspect asset metadata and structure',
  inputTypes: ['image', 'video', 'audio', 'pdf', 'text', 'data'],
  outputTypes: ['data'],
  params: [
    {
      name: 'verbose',
      type: 'boolean',
      default: false,
      description: 'Include full asset detail (tags, history count, timestamps)',
    },
  ],
  performance: 'fast',
  batchable: true,
};

export const DEV_VALIDATE_WORKFLOW: Capability = {
  name: 'developer.validate.workflow',
  description: 'Validate a workflow without executing it',
  inputTypes: ['data'],
  outputTypes: ['data'],
  params: [],
  performance: 'fast',
  batchable: false,
};

export const DEV_PROFILE: Capability = {
  name: 'developer.profile',
  description: 'Profile capability execution time',
  inputTypes: ['image', 'video', 'audio', 'pdf', 'text', 'data'],
  outputTypes: ['data'],
  params: [
    {
      name: 'iterations',
      type: 'number',
      default: 1,
      min: 1,
      description: 'Number of profiling iterations per input asset',
    },
  ],
  performance: 'slow',
  batchable: true,
};

/** 所有内置 developer 能力预设(由 codegen 从 manifest 生成) */
export const DEV_CAPABILITIES: Capability[] = [
  DEV_INSPECT_CAPABILITIES,
  DEV_INSPECT_ASSET,
  DEV_VALIDATE_WORKFLOW,
  DEV_PROFILE,
];
