/**
 * AUTO-GENERATED BY scripts/codegen-capabilities.ts — DO NOT EDIT.
 *
 * 来源:packages/capability/manifests/image.manifest.json
 * 重跑:pnpm codegen
 */
import type { Capability } from '@lokvis/schema';

export const IMAGE_RESIZE: Capability = {
  name: 'image.resize',
  description: 'Resize image to specified dimensions',
  inputTypes: ['image'],
  outputTypes: ['image'],
  params: [
    {
      name: 'width',
      type: 'number',
      required: false,
      min: 1,
      description: 'Target width in pixels',
    },
    {
      name: 'height',
      type: 'number',
      required: false,
      min: 1,
      description: 'Target height in pixels',
    },
    {
      name: 'fit',
      type: 'enum',
      default: 'cover',
      values: ['cover', 'contain', 'fill', 'inside', 'outside'],
      description: 'Fit strategy when aspect ratio differs',
    },
    { name: 'maintainAspectRatio', type: 'boolean', default: true },
  ],
  performance: 'fast',
  batchable: true,
};

export const IMAGE_COMPRESS: Capability = {
  name: 'image.compress',
  description: 'Compress image with specified quality',
  inputTypes: ['image'],
  outputTypes: ['image'],
  params: [
    { name: 'format', type: 'enum', default: 'webp', values: ['webp', 'avif', 'jpeg', 'png'] },
    { name: 'quality', type: 'number', default: 85, min: 0, max: 100 },
    {
      name: 'targetSize',
      type: 'number',
      required: false,
      description: 'Target size in bytes (optional)',
    },
  ],
  performance: 'fast',
  batchable: true,
};

export const IMAGE_CONVERT: Capability = {
  name: 'image.convert',
  description: 'Convert image to another format',
  inputTypes: ['image'],
  outputTypes: ['image'],
  params: [
    {
      name: 'format',
      type: 'enum',
      required: true,
      values: ['png', 'jpeg', 'webp', 'avif', 'gif', 'ico'],
    },
    { name: 'quality', type: 'number', default: 90, min: 0, max: 100 },
  ],
  performance: 'fast',
  batchable: true,
};

export const IMAGE_CROP: Capability = {
  name: 'image.crop',
  description: 'Crop image to a region',
  inputTypes: ['image'],
  outputTypes: ['image'],
  params: [
    { name: 'x', type: 'number', required: true, min: 0 },
    { name: 'y', type: 'number', required: true, min: 0 },
    { name: 'width', type: 'number', required: true, min: 1 },
    { name: 'height', type: 'number', required: true, min: 1 },
  ],
  performance: 'fast',
  batchable: true,
};

export const IMAGE_ROTATE: Capability = {
  name: 'image.rotate',
  description: 'Rotate image by degrees',
  inputTypes: ['image'],
  outputTypes: ['image'],
  params: [
    { name: 'angle', type: 'number', required: true, description: 'Rotation angle in degrees' },
    { name: 'background', type: 'color', default: '#ffffff' },
  ],
  performance: 'fast',
  batchable: true,
};

export const IMAGE_FLIP: Capability = {
  name: 'image.flip',
  description: 'Flip image horizontally or vertically',
  inputTypes: ['image'],
  outputTypes: ['image'],
  params: [
    { name: 'axis', type: 'enum', required: true, values: ['horizontal', 'vertical', 'both'] },
  ],
  performance: 'fast',
  batchable: true,
};

export const IMAGE_WATERMARK: Capability = {
  name: 'image.watermark',
  description: 'Add text or image watermark',
  inputTypes: ['image'],
  outputTypes: ['image'],
  params: [
    { name: 'text', type: 'string', required: false, description: 'Text watermark' },
    { name: 'image', type: 'file', required: false, description: 'Image watermark (data URL)' },
    {
      name: 'position',
      type: 'enum',
      default: 'bottom-right',
      values: ['top-left', 'top-right', 'bottom-left', 'bottom-right', 'center', 'tile'],
    },
    { name: 'opacity', type: 'number', default: 0.8, min: 0, max: 1 },
    { name: 'fontSize', type: 'number', default: 24 },
    { name: 'color', type: 'color', default: '#ffffff' },
  ],
  performance: 'fast',
  batchable: true,
};

export const IMAGE_BACKGROUND: Capability = {
  name: 'image.background',
  description: 'Set background color (for transparent images)',
  inputTypes: ['image'],
  outputTypes: ['image'],
  params: [
    { name: 'color', type: 'color', default: '#ffffff' },
  ],
  performance: 'fast',
  batchable: true,
};

export const IMAGE_FILTER: Capability = {
  name: 'image.filter',
  description: 'Apply preset filter (grayscale, invert, sepia, blur)',
  inputTypes: ['image'],
  outputTypes: ['image'],
  params: [
    {
      name: 'preset',
      type: 'enum',
      required: true,
      values: ['grayscale', 'invert', 'sepia', 'blur'],
      description: 'Filter preset name',
    },
    {
      name: 'radius',
      type: 'number',
      required: false,
      default: 4,
      min: 1,
      max: 100,
      description: 'Blur radius in pixels (blur preset only)',
    },
  ],
  performance: 'fast',
  batchable: true,
};

export const IMAGE_FAVICON: Capability = {
  name: 'image.favicon',
  description: 'Generate multi-size ICO favicon from image',
  inputTypes: ['image'],
  outputTypes: ['image'],
  params: [
    {
      name: 'sizes',
      type: 'array',
      required: false,
      items: 'number',
      description: 'Target sizes (square edge px). Default [16,32,48,256]',
    },
  ],
  performance: 'medium',
  batchable: true,
};

/** 所有内置 image 能力预设(由 codegen 从 manifest 生成) */
export const IMAGE_CAPABILITIES: Capability[] = [
  IMAGE_RESIZE,
  IMAGE_COMPRESS,
  IMAGE_CONVERT,
  IMAGE_CROP,
  IMAGE_ROTATE,
  IMAGE_FLIP,
  IMAGE_WATERMARK,
  IMAGE_BACKGROUND,
  IMAGE_FILTER,
  IMAGE_FAVICON,
];
