/**
 * 手工平台尺寸预设(过渡态数据)。
 *
 * 这些预设尚未迁入 lokvis-knowledge 仓(`@lokvis/data-platforms`),属 `source: 'manual'`
 * 的补充数据。`scripts/codegen-platform-presets.ts` 会以知识仓为唯一事实源
 * (Knowledge 存 Facts 铁律)生成 `platform.generated.ts`:
 *
 * - 知识仓已收录且带 `recommendedSize` 的规格 → 取知识仓 width/height(事实),
 *   映射到本文件中对应的预设 id(保持 id 稳定),其余展示字段沿用手工值;
 * - 知识仓未收录的平台/尺寸 → 原样保留本文件预设(`source: 'manual'`),
 *   待补入带来源(`ref:`)的知识数据后由 codegen 接管。
 *
 * 迁移约定:新增/修正平台尺寸应优先向 lokvis-knowledge 仓提交带官方来源的数据,
 * 而非在此文件硬编码。本文件只承载知识仓暂未覆盖的长尾平台。
 *
 * 排序约定:同 category 内按 platform 分组,同 platform 内按常用度从高到低。
 */
import type { PlatformSizePreset } from './platform-types.js';

export const MANUAL_PLATFORM_PRESETS: PlatformSizePreset[] = [
  // ─── social(社媒)───────────────────────────────────────
  {
    id: 'youtube.thumbnail',
    platform: 'YouTube',
    name: '视频缩略图',
    width: 1280,
    height: 720,
    category: 'social',
    description: '视频封面,16:9 比例',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'youtube.channel-art',
    platform: 'YouTube',
    name: '频道封面',
    width: 2560,
    height: 1440,
    category: 'social',
    description: '频道顶部横幅(电视端完整尺寸)',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'youtube.profile',
    platform: 'YouTube',
    name: '频道头像',
    width: 800,
    height: 800,
    category: 'social',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'youtube.short',
    platform: 'YouTube',
    name: 'Shorts 竖版',
    width: 1080,
    height: 1920,
    category: 'social',
    description: '9:16 竖版短视频',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'instagram.square',
    platform: 'Instagram',
    name: '方形帖子',
    width: 1080,
    height: 1080,
    category: 'social',
    description: '1:1 方形动态',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'instagram.portrait',
    platform: 'Instagram',
    name: '竖版帖子',
    width: 1080,
    height: 1350,
    category: 'social',
    description: '4:5 竖版(最大可见)',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'instagram.landscape',
    platform: 'Instagram',
    name: '横版帖子',
    width: 1080,
    height: 566,
    category: 'social',
    description: '1.91:1 横版',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'instagram.story',
    platform: 'Instagram',
    name: 'Story / Reel',
    width: 1080,
    height: 1920,
    category: 'social',
    description: '9:16 全屏竖版',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'instagram.profile',
    platform: 'Instagram',
    name: '头像',
    width: 320,
    height: 320,
    category: 'social',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'tiktok.video',
    platform: 'TikTok',
    name: '视频',
    width: 1080,
    height: 1920,
    category: 'social',
    description: '9:16 竖版视频',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'tiktok.profile',
    platform: 'TikTok',
    name: '头像',
    width: 200,
    height: 200,
    category: 'social',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'twitter.post',
    platform: 'Twitter / X',
    name: '帖子配图',
    width: 1200,
    height: 675,
    category: 'social',
    description: '16:9 单图/多图',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'twitter.header',
    platform: 'Twitter / X',
    name: '横幅',
    width: 1500,
    height: 500,
    category: 'social',
    description: '3:1 个人页横幅',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'twitter.profile',
    platform: 'Twitter / X',
    name: '头像',
    width: 400,
    height: 400,
    category: 'social',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'facebook.cover',
    platform: 'Facebook',
    name: '封面',
    width: 1640,
    height: 856,
    category: 'social',
    description: '个人/公共主页封面',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'facebook.post',
    platform: 'Facebook',
    name: '帖子配图',
    width: 1200,
    height: 630,
    category: 'social',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'facebook.profile',
    platform: 'Facebook',
    name: '头像',
    width: 320,
    height: 320,
    category: 'social',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'linkedin.post',
    platform: 'LinkedIn',
    name: '帖子配图',
    width: 1200,
    height: 627,
    category: 'social',
    description: '1.91:1 链接预览',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'linkedin.cover',
    platform: 'LinkedIn',
    name: '个人封面',
    width: 1584,
    height: 396,
    category: 'social',
    description: '4:1 横幅',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'linkedin.profile',
    platform: 'LinkedIn',
    name: '头像',
    width: 400,
    height: 400,
    category: 'social',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'linkedin.company-logo',
    platform: 'LinkedIn',
    name: '公司 Logo',
    width: 300,
    height: 300,
    category: 'social',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'pinterest.pin',
    platform: 'Pinterest',
    name: '标准 Pin',
    width: 1000,
    height: 1500,
    category: 'social',
    description: '2:3 竖版 Pin',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'pinterest.square',
    platform: 'Pinterest',
    name: '方形 Pin',
    width: 1000,
    height: 1000,
    category: 'social',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'snapchat.story',
    platform: 'Snapchat',
    name: 'Story / Ad',
    width: 1080,
    height: 1920,
    category: 'social',
    description: '9:16 全屏',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'reddit.post',
    platform: 'Reddit',
    name: '帖子图片',
    width: 1024,
    height: 1024,
    category: 'social',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'reddit.banner',
    platform: 'Reddit',
    name: '版块横幅',
    width: 1920,
    height: 256,
    category: 'social',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'whatsapp.status',
    platform: 'WhatsApp',
    name: 'Status',
    width: 1080,
    height: 1920,
    category: 'social',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'whatsapp.profile',
    platform: 'WhatsApp',
    name: '头像',
    width: 640,
    height: 640,
    category: 'social',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'wechat.article',
    platform: 'WeChat',
    name: '公众号封面',
    width: 900,
    height: 500,
    category: 'social',
    description: '1.8:1 头图',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'wechat.moment',
    platform: 'WeChat',
    name: '朋友圈',
    width: 1080,
    height: 1080,
    category: 'social',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'xiaohongshu.post',
    platform: '小红书',
    name: '笔记配图',
    width: 1080,
    height: 1440,
    category: 'social',
    description: '3:4 竖版',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'discord.avatar',
    platform: 'Discord',
    name: '头像',
    width: 128,
    height: 128,
    category: 'social',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'discord.banner',
    platform: 'Discord',
    name: '服务器横幅',
    width: 600,
    height: 240,
    category: 'social',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'telegram.profile',
    platform: 'Telegram',
    name: '头像',
    width: 512,
    height: 512,
    category: 'social',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'twitch.profile',
    platform: 'Twitch',
    name: '头像',
    width: 256,
    height: 256,
    category: 'social',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'twitch.banner',
    platform: 'Twitch',
    name: '横幅',
    width: 1200,
    height: 480,
    category: 'social',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'spotify.cover',
    platform: 'Spotify',
    name: '歌单封面',
    width: 300,
    height: 300,
    category: 'social',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },

  // ─── ecommerce(电商)──────────────────────────────────
  {
    id: 'shopify.product',
    platform: 'Shopify',
    name: '商品主图',
    width: 2048,
    height: 2048,
    category: 'ecommerce',
    description: '方形商品图',
    recommendedFormat: 'jpeg',
    recommendedFit: 'contain',
  },
  {
    id: 'shopify.banner',
    platform: 'Shopify',
    name: '首页横幅',
    width: 1200,
    height: 400,
    category: 'ecommerce',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'shopify.thumbnail',
    platform: 'Shopify',
    name: '缩略图',
    width: 800,
    height: 800,
    category: 'ecommerce',
    recommendedFormat: 'jpeg',
    recommendedFit: 'contain',
  },
  {
    id: 'etsy.listing',
    platform: 'Etsy',
    name: '商品图',
    width: 2000,
    height: 2000,
    category: 'ecommerce',
    recommendedFormat: 'jpeg',
    recommendedFit: 'contain',
  },
  {
    id: 'etsy.thumbnail',
    platform: 'Etsy',
    name: '缩略图',
    width: 570,
    height: 456,
    category: 'ecommerce',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'etsy.header',
    platform: 'Etsy',
    name: '店铺横幅',
    width: 1200,
    height: 300,
    category: 'ecommerce',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'amazon.product',
    platform: 'Amazon',
    name: '商品主图',
    width: 2000,
    height: 2000,
    category: 'ecommerce',
    description: '主图必须为纯白背景',
    recommendedFormat: 'jpeg',
    recommendedFit: 'contain',
  },
  {
    id: 'amazon.header',
    platform: 'Amazon',
    name: '品牌横幅',
    width: 1500,
    height: 315,
    category: 'ecommerce',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'ebay.listing',
    platform: 'eBay',
    name: '商品图',
    width: 1600,
    height: 1600,
    category: 'ecommerce',
    recommendedFormat: 'jpeg',
    recommendedFit: 'contain',
  },
  {
    id: 'taobao.product',
    platform: '淘宝 / 天猫',
    name: '商品主图',
    width: 800,
    height: 800,
    category: 'ecommerce',
    recommendedFormat: 'jpeg',
    recommendedFit: 'contain',
  },
  {
    id: 'taobao.detail',
    platform: '淘宝 / 天猫',
    name: '详情图',
    width: 750,
    height: 1000,
    category: 'ecommerce',
    recommendedFormat: 'jpeg',
    recommendedFit: 'contain',
  },

  // ─── video(视频封面/缩略图)────────────────────────────
  {
    id: 'video.thumbnail-hd',
    platform: '通用视频',
    name: 'HD 缩略图',
    width: 1280,
    height: 720,
    category: 'video',
    description: '16:9 720p',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'video.thumbnail-4k',
    platform: '通用视频',
    name: '4K 缩略图',
    width: 3840,
    height: 2160,
    category: 'video',
    description: '16:9 4K',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'video.vertical',
    platform: '通用视频',
    name: '竖版视频',
    width: 1080,
    height: 1920,
    category: 'video',
    description: '9:16 竖版',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'video.square',
    platform: '通用视频',
    name: '方形视频',
    width: 1080,
    height: 1080,
    category: 'video',
    description: '1:1 方形',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },

  // ─── print(打印)──────────────────────────────────────
  {
    id: 'print.a4-300dpi',
    platform: '打印',
    name: 'A4 (300 DPI)',
    width: 2480,
    height: 3508,
    category: 'print',
    description: 'A4 纸 300 DPI 像素尺寸',
    recommendedFormat: 'png',
    recommendedFit: 'contain',
  },
  {
    id: 'print.a4-150dpi',
    platform: '打印',
    name: 'A4 (150 DPI)',
    width: 1240,
    height: 1754,
    category: 'print',
    description: 'A4 纸 150 DPI(草稿)',
    recommendedFormat: 'png',
    recommendedFit: 'contain',
  },
  {
    id: 'print.a3-300dpi',
    platform: '打印',
    name: 'A3 (300 DPI)',
    width: 3508,
    height: 4961,
    category: 'print',
    description: 'A3 纸 300 DPI',
    recommendedFormat: 'png',
    recommendedFit: 'contain',
  },
  {
    id: 'print.business-card',
    platform: '打印',
    name: '名片(90×54mm)',
    width: 1063,
    height: 638,
    category: 'print',
    description: '90×54mm 名片 300 DPI',
    recommendedFormat: 'png',
    recommendedFit: 'contain',
  },
  {
    id: 'print.photo-4x6',
    platform: '打印',
    name: '4×6 英寸相片',
    width: 1200,
    height: 1800,
    category: 'print',
    description: '4×6 英寸 300 DPI',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },

  // ─── other(通用)──────────────────────────────────────
  {
    id: 'web.banner',
    platform: '通用 Web',
    name: '网站横幅',
    width: 1920,
    height: 600,
    category: 'other',
    recommendedFormat: 'webp',
    recommendedFit: 'cover',
  },
  {
    id: 'web.email-header',
    platform: '通用 Web',
    name: '邮件头图',
    width: 1200,
    height: 400,
    category: 'other',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'web.favicon',
    platform: '通用 Web',
    name: 'Favicon',
    width: 64,
    height: 64,
    category: 'other',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'web.og-image',
    platform: '通用 Web',
    name: 'Open Graph 图',
    width: 1200,
    height: 630,
    category: 'other',
    description: '社交分享预览图',
    recommendedFormat: 'jpeg',
    recommendedFit: 'cover',
  },
  {
    id: 'app.icon-ios',
    platform: 'App',
    name: 'iOS App Icon',
    width: 1024,
    height: 1024,
    category: 'other',
    description: 'iOS 单尺寸图标(自动派生)',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
  {
    id: 'app.icon-android',
    platform: 'App',
    name: 'Android xxxhdpi',
    width: 192,
    height: 192,
    category: 'other',
    recommendedFormat: 'png',
    recommendedFit: 'cover',
  },
];
